export type ManualQaPriority = "P0" | "P1" | "P2";

export interface ManualQaTest {
  id: string;
  section: string;
  priority: ManualQaPriority;
  title: string;
  route: string;
  steps: string[];
  expected: string;
  automatedCoverage: string;
}

export const manualQaSections = [
  "Auth and onboarding",
  "Reviews",
  "Visibility and privacy",
  "Circle",
  "Notifications",
  "Search",
  "Trending and restaurants",
  "Common restaurants",
  "Settings and profile",
  "Likes, comments, wishlist",
  "Mobile layout",
  "Production integrations",
  "Errors and edge cases",
];

export const manualQaTests: ManualQaTest[] = [
  {
    id: "QA-001",
    section: "Auth and onboarding",
    priority: "P0",
    title: "Signup, onboarding, login, logout",
    route: "/login",
    steps: [
      "Create or use a clean test account.",
      "Complete onboarding with name and username.",
      "Log out, log back in, refresh the page.",
    ],
    expected: "Session persists after refresh, logout clears access, and protected routes redirect logged-out users.",
    automatedCoverage: "Partially covered by Playwright auth smoke and node auth tests.",
  },
  {
    id: "QA-002",
    section: "Auth and onboarding",
    priority: "P0",
    title: "Password reset flow",
    route: "/auth/reset-password",
    steps: ["Open reset password flow from production.", "Request reset email.", "Open the email link and set a new password.", "Log in with the new password."],
    expected: "Reset email redirects to the production app, the password updates, and login works afterward.",
    automatedCoverage: "Prerender/build is covered; live email redirect is manual-first.",
  },
  {
    id: "QA-003",
    section: "Reviews",
    priority: "P0",
    title: "Create public review with required fields",
    route: "/reviews/new",
    steps: ["Open the review form.", "Try submitting empty fields.", "Fill restaurant, dish/rating, text, and post."],
    expected: "Validation appears for missing fields, then the review posts and appears on feed/profile.",
    automatedCoverage: "Covered by node API tests and Playwright desktop/mobile smoke.",
  },
  {
    id: "QA-004",
    section: "Reviews",
    priority: "P0",
    title: "Create circle and only-me reviews",
    route: "/reviews/new",
    steps: ["Create one circle review.", "Create one only-me review.", "Check feed/profile as owner and outsider."],
    expected: "Owner can see both. Outsider cannot see circle or only-me content.",
    automatedCoverage: "Covered by visibility logic and Playwright smoke; manual verifies real UI.",
  },
  {
    id: "QA-005",
    section: "Reviews",
    priority: "P1",
    title: "Edit and delete review",
    route: "/me",
    steps: ["Open your own review detail.", "Edit the review.", "Delete another test review."],
    expected: "Edits persist, deleted review disappears from feed/profile/explore surfaces.",
    automatedCoverage: "API ownership covered by node tests; browser edit/delete needs manual verification.",
  },
  {
    id: "QA-006",
    section: "Reviews",
    priority: "P0",
    title: "Photo upload and storage render",
    route: "/reviews/new",
    steps: [
      "Attach a supported image from a logged-in production test account.",
      "Post the review.",
      "Open the detail page, profile card, and feed/explore card where applicable.",
      "Hard refresh and confirm the image still loads.",
    ],
    expected: "Photo uploads to Supabase Storage, renders after refresh, and does not break layout on desktop or mobile.",
    automatedCoverage: "Storage policies have schema guards; live upload/render is manual-first.",
  },
  {
    id: "QA-007",
    section: "Visibility and privacy",
    priority: "P0",
    title: "Direct privacy smoke with three users",
    route: "/",
    steps: [
      "Use owner, circle member, and outsider accounts.",
      "Check public, circle, and only-me reviews across feed, profile, and detail pages.",
      "Repeat after hard refresh.",
    ],
    expected: "Public is visible. Circle is visible only to allowed circle members. Only-me is owner-only.",
    automatedCoverage: "Covered by node privacy tests and Playwright smoke; manual verifies live browser behavior.",
  },
  {
    id: "QA-008",
    section: "Visibility and privacy",
    priority: "P0",
    title: "Supabase RLS privacy verification",
    route: "Supabase SQL/API",
    steps: [
      "Apply all migrations.",
      "Verify old open read policies are gone.",
      "Directly query as outsider for circle and only-me review IDs.",
    ],
    expected: "Outsider direct reads return no private rows or private engagement rows.",
    automatedCoverage: "Static migration guards exist; live DB check is manual.",
  },
  {
    id: "QA-009",
    section: "Circle",
    priority: "P0",
    title: "Circle core relationship flows",
    route: "/explore",
    steps: [
      "Use three test accounts: A, B public, and C private.",
      "As A, add public account B and confirm the button changes to In Circle.",
      "As A, request private account C, then cancel the request and confirm the button returns to Add.",
      "As A, request C again; as C, accept from notifications and confirm both users see the final relationship state after refresh.",
      "Remove the relationship and confirm the button/list state updates after refresh.",
    ],
    expected: "Public add, private request, cancel, accept, remove, and refresh persistence all work without stale or duplicate Circle states.",
    automatedCoverage: "Circle has strong node tests plus desktop/mobile E2E smoke; this manual item replaces the old deep-dive Circle page as the go-live gate.",
  },
  {
    id: "QA-010",
    section: "Notifications",
    priority: "P0",
    title: "Circle request and accept notifications",
    route: "/notifications",
    steps: ["Send a private account request.", "Open receiver notifications.", "Accept or reject.", "Refresh both users."],
    expected: "Notification appears, actions work, stale notification disappears or updates.",
    automatedCoverage: "Covered by node notification tests and Playwright smoke; manual verifies UX.",
  },
  {
    id: "QA-011",
    section: "Notifications",
    priority: "P1",
    title: "Like and comment notifications",
    route: "/notifications",
    steps: ["Like another user's review.", "Comment on it.", "Open recipient notifications.", "Mark read/delete if available."],
    expected: "Unread badge updates and notification actions do not show stale state.",
    automatedCoverage: "Covered by API/E2E smoke; manual verifies bell/list behavior.",
  },
  {
    id: "QA-012",
    section: "Search",
    priority: "P0",
    title: "People, restaurant, and dish search",
    route: "/explore",
    steps: ["Search a user by name.", "Search restaurants.", "Search dishes, including spaces and special characters."],
    expected: "Results are relevant, empty states are clear, and cards fit on mobile.",
    automatedCoverage: "Partially covered by search tests and E2E smoke.",
  },
  {
    id: "QA-013",
    section: "Trending and restaurants",
    priority: "P0",
    title: "Explore public discovery privacy",
    route: "/explore",
    steps: ["Create public, circle, and only-me reviews.", "Open Explore as owner and outsider."],
    expected: "Only public eligible content appears in Explore discovery.",
    automatedCoverage: "Covered by node privacy tests and E2E smoke.",
  },
  {
    id: "QA-014",
    section: "Trending and restaurants",
    priority: "P1",
    title: "Restaurant detail visibility",
    route: "/trending/[restaurant]",
    steps: [
      "Open restaurant detail pages as owner, circle member, and outsider.",
      "Compare visible posts for the same restaurant across all three accounts.",
    ],
    expected: "Restaurant posts are filtered by viewer visibility.",
    automatedCoverage: "Covered by node page wiring tests; manual verifies route UI.",
  },
  {
    id: "QA-015",
    section: "Common restaurants",
    priority: "P0",
    title: "Common restaurant badge",
    route: "/explore",
    steps: ["Open a circle member profile.", "Confirm badge/count.", "Remove circle relationship and refresh."],
    expected: "Badge appears only when appropriate and does not leak hidden/private restaurants.",
    automatedCoverage: "Covered by common restaurant tests and E2E smoke.",
  },
  {
    id: "QA-016",
    section: "Settings and profile",
    priority: "P0",
    title: "Profile edit and public/private switch",
    route: "/me/settings",
    steps: ["Edit display details.", "Switch account public/private.", "Open profile from another account."],
    expected: "Profile updates persist and private account Circle behavior changes correctly.",
    automatedCoverage: "Partially covered by E2E private request smoke.",
  },
  {
    id: "QA-017",
    section: "Settings and profile",
    priority: "P1",
    title: "Avatar and username validation",
    route: "/me/settings/edit",
    steps: ["Upload/change avatar.", "Try invalid and duplicate usernames.", "Save valid changes."],
    expected: "Invalid values are blocked, valid updates persist, avatar displays correctly.",
    automatedCoverage: "Manual-first.",
  },
  {
    id: "QA-018",
    section: "Likes, comments, wishlist",
    priority: "P0",
    title: "Like/unlike and comment create/delete",
    route: "/",
    steps: ["Like and unlike a review.", "Create a comment.", "Delete your comment.", "Try deleting someone else's comment."],
    expected: "Counts update correctly, own delete works, other-user delete is blocked.",
    automatedCoverage: "API tests cover authorization; E2E covers like/comment notification smoke.",
  },
  {
    id: "QA-019",
    section: "Likes, comments, wishlist",
    priority: "P1",
    title: "Wishlist add/remove",
    route: "/me/settings/saved",
    steps: ["Add a review/restaurant to wishlist.", "Open saved page.", "Remove it and refresh."],
    expected: "Saved state persists only for the owner and does not expose private reviews.",
    automatedCoverage: "Wishlist helper and RLS migration guards exist; browser flow is manual.",
  },
  {
    id: "QA-020",
    section: "Mobile layout",
    priority: "P0",
    title: "Mobile core navigation and no overflow",
    route: "/",
    steps: ["Use a phone viewport.", "Tap bottom nav routes.", "Check feed, search, review form, profile, notifications."],
    expected: "Bottom nav works, no horizontal overflow, buttons and badges do not overlap.",
    automatedCoverage: "Covered by mobile Playwright smoke; manual verifies real device feel.",
  },
  {
    id: "QA-021",
    section: "Errors and edge cases",
    priority: "P1",
    title: "Refresh, back button, double-click actions",
    route: "/",
    steps: ["Double-click like/comment/circle actions.", "Use browser back after actions.", "Refresh after mutations."],
    expected: "No duplicate rows, stale buttons recover, and final state remains correct.",
    automatedCoverage: "Partially covered by Circle QA and API tests.",
  },
  {
    id: "QA-022",
    section: "Errors and edge cases",
    priority: "P1",
    title: "Empty and no-data states",
    route: "/explore",
    steps: ["Use empty searches.", "Open pages with no reviews/notifications/saved items.", "Try duplicate names."],
    expected: "Empty states are clear and layout remains stable.",
    automatedCoverage: "Manual-first.",
  },
  {
    id: "QA-023",
    section: "Production integrations",
    priority: "P0",
    title: "Google sign-in production redirect",
    route: "/login",
    steps: [
      "Open production login.",
      "Click Google sign-in.",
      "Complete Google auth with a test account.",
      "Confirm Supabase returns to the production app and the session persists after refresh.",
    ],
    expected: "Google OAuth uses the configured Supabase callback and lands in the app without redirect errors.",
    automatedCoverage: "Auth callback route is unit-tested; live Google/Supabase OAuth is manual-first.",
  },
  {
    id: "QA-024",
    section: "Production integrations",
    priority: "P0",
    title: "Google Places restaurant selection and saved location",
    route: "/reviews/new",
    steps: [
      "Open production review form.",
      "Type a real restaurant name and confirm suggestions appear.",
      "Try posting without selecting a suggestion.",
      "Select a suggestion, post the review, and open the created post.",
      "Click the compact location under the restaurant name.",
    ],
    expected: "Manual typing is blocked, dropdown selection works, area/address appears under the post, and the location opens Google Maps using stored coordinates.",
    automatedCoverage: "Places API routes are unit-tested and E2E mocks selection; live Google Places production key/config is manual-first.",
  },
  {
    id: "QA-025",
    section: "Production integrations",
    priority: "P0",
    title: "Production environment variables and route health",
    route: "Vercel + production app",
    steps: [
      "Confirm Vercel has Supabase, service role, and Google Places environment variables set for Production.",
      "Open /login, /auth/reset-password, /reviews/new, and /explore after deploy.",
      "Check Vercel function logs while using Google Places and auth routes.",
    ],
    expected: "No prerender env errors, protected routes redirect correctly, and server routes do not log missing API key errors.",
    automatedCoverage: "Local build and route unit tests cover code shape; deployed environment configuration is manual-first.",
  },
  {
    id: "QA-026",
    section: "Production integrations",
    priority: "P0",
    title: "Launch gate commands completed",
    route: "Local terminal + Playwright report",
    steps: [
      "Run npm test.",
      "Run npm run test:coverage:html and confirm the coverage summary is acceptable.",
      "Run npm run build.",
      "Run node scripts/seed-e2e.mjs && npm run test:e2e -- --workers=1.",
      "Open the Playwright report if any retry/failure happened and confirm the final run is clean.",
    ],
    expected: "Unit/API tests, coverage, production build, and the full E2E suite all pass before deployment sign-off.",
    automatedCoverage: "The /qa Automated and E2E tabs list the exact commands; this manual item records go-live sign-off.",
  },
  {
    id: "QA-027",
    section: "Settings and profile",
    priority: "P1",
    title: "Delete account safety",
    route: "/me/settings",
    steps: [
      "Create or use a disposable production test account.",
      "Post a test review and create one comment/like if possible.",
      "Use the delete account flow from settings.",
      "Try logging in again and check that another user's account and content remain unaffected.",
    ],
    expected: "Only the authenticated disposable account is removed or disabled; other users and their content are untouched.",
    automatedCoverage: "Delete-account API authorization is covered by node route tests; live destructive UX is manual-first.",
  },
  {
    id: "QA-028",
    section: "Circle",
    priority: "P0",
    title: "Circle feed source-of-truth and old membership posts",
    route: "/",
    steps: [
      "Use an account with existing Circle relationships that were created before the latest Circle migration.",
      "Confirm the old Circle owners appear in the Circle feed after a hard refresh.",
      "Create a new public post and a new circle post from one Circle owner.",
      "Log back in as the viewer and open the Circle feed.",
      "Remove one Circle relationship and refresh the Circle feed again.",
    ],
    expected: "Old and new public/circle posts from joined Circle owners appear, me-only posts stay hidden, and removed relationships disappear from the feed without stale posts.",
    automatedCoverage: "Covered by Circle DB source-of-truth tests, feed visibility tests, page wiring tests, and Playwright circle feed smoke.",
  },
  {
    id: "QA-029",
    section: "Reviews",
    priority: "P0",
    title: "Delete last restaurant post redirects safely",
    route: "/people/[username]/[restaurant]",
    steps: [
      "Create a unique test review at a restaurant with only one post for that user.",
      "Open the user's restaurant detail page.",
      "Use the three-dot menu on the post and confirm Delete post.",
      "Observe the route after deletion and refresh the resulting page.",
    ],
    expected: "The deleted post disappears, stats/counts no longer include it, and the app redirects to the user profile instead of showing a not-found restaurant page.",
    automatedCoverage: "Covered by review delete UI regression tests and Playwright delete-last-post smoke.",
  },
  {
    id: "QA-030",
    section: "Visibility and privacy",
    priority: "P0",
    title: "Stats, places, and dishes visibility matrix",
    route: "/people/[username], /explore, /trending/[restaurant], /dishes",
    steps: [
      "Use seeded public, circle, and private reviews for a public account and a private account.",
      "Compare profile stats as owner, stranger, pending requester, and circle member.",
      "Search the same seeded restaurants in /explore and dishes in /dishes.",
      "Accept a pending Circle request and repeat the profile, restaurant, and dish checks.",
    ],
    expected: "Strangers and pending requesters see public-only stats. Circle members see public plus circle stats. Owners see public plus circle plus private stats. Explore discovery and /dishes expose public-only data.",
    automatedCoverage: "Covered by stats visibility matrix tests, page wiring tests, RLS guards, and Playwright visibility/dish smoke.",
  },
];

export const manualQaSmokeIds = new Set([
  "QA-001",
  "QA-002",
  "QA-003",
  "QA-004",
  "QA-006",
  "QA-007",
  "QA-008",
  "QA-009",
  "QA-010",
  "QA-012",
  "QA-013",
  "QA-015",
  "QA-016",
  "QA-018",
  "QA-020",
  "QA-023",
  "QA-024",
  "QA-025",
  "QA-026",
  "QA-028",
  "QA-029",
  "QA-030",
]);
