export type ManualQaPriority = "P0" | "P1" | "P2";

export interface ManualQaTest {
  id: string;
  section: string;
  priority: ManualQaPriority;
  title: string;
  route: string;
  steps: string[];
  expected: string;
  automatedCoverage: string;
}

export const manualQaSections = [
  "Auth and onboarding",
  "Reviews",
  "Visibility and privacy",
  "Circle",
  "Notifications",
  "Search",
  "Trending and restaurants",
  "Common restaurants",
  "Settings and profile",
  "Likes, comments, wishlist",
  "Mobile layout",
  "Errors and edge cases",
];

export const manualQaTests: ManualQaTest[] = [
  {
    id: "QA-001",
    section: "Auth and onboarding",
    priority: "P0",
    title: "Signup, onboarding, login, logout",
    route: "/login",
    steps: [
      "Create or use a clean test account.",
      "Complete onboarding with name and username.",
      "Log out, log back in, refresh the page.",
    ],
    expected: "Session persists after refresh, logout clears access, and protected routes redirect logged-out users.",
    automatedCoverage: "Partially covered by Playwright auth smoke and node auth tests.",
  },
  {
    id: "QA-002",
    section: "Auth and onboarding",
    priority: "P1",
    title: "Password reset flow",
    route: "/auth/reset-password",
    steps: ["Open reset password flow.", "Request reset email.", "Confirm the UI handles success and errors."],
    expected: "Reset request succeeds or shows a clear error without breaking login.",
    automatedCoverage: "Manual-first.",
  },
  {
    id: "QA-003",
    section: "Reviews",
    priority: "P0",
    title: "Create public review with required fields",
    route: "/reviews/new",
    steps: ["Open the review form.", "Try submitting empty fields.", "Fill restaurant, dish/rating, text, and post."],
    expected: "Validation appears for missing fields, then the review posts and appears on feed/profile.",
    automatedCoverage: "Covered by node API tests and Playwright desktop/mobile smoke.",
  },
  {
    id: "QA-004",
    section: "Reviews",
    priority: "P0",
    title: "Create circle and only-me reviews",
    route: "/reviews/new",
    steps: ["Create one circle review.", "Create one only-me review.", "Check feed/profile as owner and outsider."],
    expected: "Owner can see both. Outsider cannot see circle or only-me content.",
    automatedCoverage: "Covered by visibility logic and Playwright smoke; manual verifies real UI.",
  },
  {
    id: "QA-005",
    section: "Reviews",
    priority: "P1",
    title: "Edit and delete review",
    route: "/me",
    steps: ["Open your own review detail.", "Edit the review.", "Delete another test review."],
    expected: "Edits persist, deleted review disappears from feed/profile/trending.",
    automatedCoverage: "API ownership covered by node tests; browser edit/delete needs manual verification.",
  },
  {
    id: "QA-006",
    section: "Reviews",
    priority: "P1",
    title: "Photo upload review",
    route: "/reviews/new",
    steps: ["Attach a supported image.", "Post the review.", "Open the detail page and profile card."],
    expected: "Photo uploads, renders, and does not break layout on mobile.",
    automatedCoverage: "Manual-first.",
  },
  {
    id: "QA-007",
    section: "Visibility and privacy",
    priority: "P0",
    title: "Direct privacy smoke with three users",
    route: "/",
    steps: [
      "Use owner, circle member, and outsider accounts.",
      "Check public, circle, and only-me reviews across feed, profile, and detail pages.",
      "Repeat after hard refresh.",
    ],
    expected: "Public is visible. Circle is visible only to allowed circle members. Only-me is owner-only.",
    automatedCoverage: "Covered by node privacy tests and Playwright smoke; manual verifies live browser behavior.",
  },
  {
    id: "QA-008",
    section: "Visibility and privacy",
    priority: "P0",
    title: "Supabase RLS privacy verification",
    route: "Supabase SQL/API",
    steps: [
      "Apply all migrations.",
      "Verify old open read policies are gone.",
      "Directly query as outsider for circle and only-me review IDs.",
    ],
    expected: "Outsider direct reads return no private rows or private engagement rows.",
    automatedCoverage: "Static migration guards exist; live DB check is manual.",
  },
  {
    id: "QA-009",
    section: "Circle",
    priority: "P0",
    title: "Circle dedicated checklist",
    route: "/qa/circle",
    steps: ["Open the Circle QA page.", "Run high-priority and smoke cases.", "Export or save notes."],
    expected: "Add, request, accept, reject, cancel, remove, stale state, and persistence cases pass.",
    automatedCoverage: "Circle has strong node tests plus desktop/mobile E2E smoke.",
  },
  {
    id: "QA-010",
    section: "Notifications",
    priority: "P0",
    title: "Circle request and accept notifications",
    route: "/notifications",
    steps: ["Send a private account request.", "Open receiver notifications.", "Accept or reject.", "Refresh both users."],
    expected: "Notification appears, actions work, stale notification disappears or updates.",
    automatedCoverage: "Covered by node notification tests and Playwright smoke; manual verifies UX.",
  },
  {
    id: "QA-011",
    section: "Notifications",
    priority: "P1",
    title: "Like and comment notifications",
    route: "/notifications",
    steps: ["Like another user's review.", "Comment on it.", "Open recipient notifications.", "Mark read/delete if available."],
    expected: "Unread badge updates and notification actions do not show stale state.",
    automatedCoverage: "Covered by API/E2E smoke; manual verifies bell/list behavior.",
  },
  {
    id: "QA-012",
    section: "Search",
    priority: "P0",
    title: "People, restaurant, and dish search",
    route: "/people",
    steps: ["Search a user by name.", "Search restaurants.", "Search dishes, including spaces and special characters."],
    expected: "Results are relevant, empty states are clear, and cards fit on mobile.",
    automatedCoverage: "Partially covered by search tests and E2E smoke.",
  },
  {
    id: "QA-013",
    section: "Trending and restaurants",
    priority: "P0",
    title: "Global trending privacy",
    route: "/trending",
    steps: ["Create public, circle, and only-me reviews.", "Open global trending as owner and outsider."],
    expected: "Only public eligible content appears in global trending.",
    automatedCoverage: "Covered by node privacy tests and E2E smoke.",
  },
  {
    id: "QA-014",
    section: "Trending and restaurants",
    priority: "P1",
    title: "Restaurant detail visibility",
    route: "/trending",
    steps: [
      "Open restaurant detail pages as owner, circle member, and outsider.",
      "Compare visible posts for the same restaurant across all three accounts.",
    ],
    expected: "Restaurant posts are filtered by viewer visibility.",
    automatedCoverage: "Covered by node page wiring tests; manual verifies route UI.",
  },
  {
    id: "QA-015",
    section: "Common restaurants",
    priority: "P0",
    title: "Common restaurant badge",
    route: "/people",
    steps: ["Open a circle member profile.", "Confirm badge/count.", "Remove circle relationship and refresh."],
    expected: "Badge appears only when appropriate and does not leak hidden/private restaurants.",
    automatedCoverage: "Covered by common restaurant tests and E2E smoke.",
  },
  {
    id: "QA-016",
    section: "Settings and profile",
    priority: "P0",
    title: "Profile edit and public/private switch",
    route: "/me/settings",
    steps: ["Edit display details.", "Switch account public/private.", "Open profile from another account."],
    expected: "Profile updates persist and private account Circle behavior changes correctly.",
    automatedCoverage: "Partially covered by E2E private request smoke.",
  },
  {
    id: "QA-017",
    section: "Settings and profile",
    priority: "P1",
    title: "Avatar and username validation",
    route: "/me/settings/edit",
    steps: ["Upload/change avatar.", "Try invalid and duplicate usernames.", "Save valid changes."],
    expected: "Invalid values are blocked, valid updates persist, avatar displays correctly.",
    automatedCoverage: "Manual-first.",
  },
  {
    id: "QA-018",
    section: "Likes, comments, wishlist",
    priority: "P0",
    title: "Like/unlike and comment create/delete",
    route: "/",
    steps: ["Like and unlike a review.", "Create a comment.", "Delete your comment.", "Try deleting someone else's comment."],
    expected: "Counts update correctly, own delete works, other-user delete is blocked.",
    automatedCoverage: "API tests cover authorization; E2E covers like/comment notification smoke.",
  },
  {
    id: "QA-019",
    section: "Likes, comments, wishlist",
    priority: "P1",
    title: "Wishlist add/remove",
    route: "/me/settings/saved",
    steps: ["Add a review/restaurant to wishlist.", "Open saved page.", "Remove it and refresh."],
    expected: "Saved state persists only for the owner and does not expose private reviews.",
    automatedCoverage: "Wishlist helper and RLS migration guards exist; browser flow is manual.",
  },
  {
    id: "QA-020",
    section: "Mobile layout",
    priority: "P0",
    title: "Mobile core navigation and no overflow",
    route: "/",
    steps: ["Use a phone viewport.", "Tap bottom nav routes.", "Check feed, search, review form, profile, notifications."],
    expected: "Bottom nav works, no horizontal overflow, buttons and badges do not overlap.",
    automatedCoverage: "Covered by mobile Playwright smoke; manual verifies real device feel.",
  },
  {
    id: "QA-021",
    section: "Errors and edge cases",
    priority: "P1",
    title: "Refresh, back button, double-click actions",
    route: "/",
    steps: ["Double-click like/comment/circle actions.", "Use browser back after actions.", "Refresh after mutations."],
    expected: "No duplicate rows, stale buttons recover, and final state remains correct.",
    automatedCoverage: "Partially covered by Circle QA and API tests.",
  },
  {
    id: "QA-022",
    section: "Errors and edge cases",
    priority: "P1",
    title: "Empty and no-data states",
    route: "/people",
    steps: ["Use empty searches.", "Open pages with no reviews/notifications/saved items.", "Try duplicate names."],
    expected: "Empty states are clear and layout remains stable.",
    automatedCoverage: "Manual-first.",
  },
];

export const manualQaSmokeIds = new Set([
  "QA-001",
  "QA-003",
  "QA-004",
  "QA-007",
  "QA-008",
  "QA-009",
  "QA-010",
  "QA-012",
  "QA-013",
  "QA-015",
  "QA-016",
  "QA-018",
  "QA-020",
]);
